from ast import For
import time
import colorama
from colorama import Fore, Back, Style
colorama.init(autoreset=True)

print(f'{Fore.YELLOW}     ____  ____   _____ ______   ____  _____ ____   ____  ___ ___')
print(f'{Fore.YELLOW}    |    ||    \ / ___/|      | /    |/ ___/|    \ /    ||   |   |')
print(f'{Fore.YELLOW}     |  | |  _  (   \_ |      ||  o  (   \_ |  o  )  o  || _   _ |')
print(f'{Fore.YELLOW}     |  | |  |  |\__  ||_|  |_||     |\__  ||   _/|     ||  \_/  |')
print(f'{Fore.YELLOW}     |  | |  |  |/  \ |  |  |  |  _  |/  \ ||  |  |  _  ||   |   |')
print(f'{Fore.YELLOW}     |  | |  |  |\    |  |  |  |  |  |\    ||  |  |  |  ||   |   |')
print(f'{Fore.YELLOW}    |____||__|__| \___|  |__|  |__|__| \___||__|  |__|__||___|___|v1')
print(f'{Fore.YELLOW}    @_.aurel_vllahi            ')
print(f'{Fore.YELLOW}AUREL INSTAGRAM TOOL v1\n')

USERNAME = input('USERNAME: ')
print('Trying to finde this account: ' + USERNAME)
time.sleep(4)
print('Account Finded\n\n')
time.sleep(2)
print('Please Wait... \n\n\n\n')
time.sleep(4)


print(f'{Fore.BLUE}Bot 1 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 2 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 3 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(5)
print(f'{Fore.BLUE}Bot 4 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 5 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 6 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 7 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 8 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 9 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 10 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 11 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 12 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 13 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 14 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 15 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 16 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 17 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 18 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 19 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 20 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 21 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 22 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 23 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 24 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 25 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 26 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 27 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 28 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 29 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 30 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 31 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 32 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 33 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 34 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 35 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 36 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 37 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 38 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 39 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 40 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 41 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 42 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 43 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 44 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 45 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 46 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 47 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 48 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 49 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 50 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 51 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 52 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 53 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 54 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 55 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 56 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 57 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 58 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 59 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 60 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 61 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 62 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 63 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 64 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 65 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 66 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 67 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 68 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 69 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 70 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 71 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 72 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 73 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 74 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 75 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 76 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 77 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 78 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 79 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 80 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 81 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 82 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 83 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 84 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 85 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 86 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 87 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 88 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 89 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 90 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 91 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 92 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 93 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 94 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 95 trying to Report...  ')
time.sleep(1)
print(f'{Fore.RED}Failed\n')
time.sleep(3)
print(f'{Fore.BLUE}Bot 96 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 97 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 98 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 99 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)
print(f'{Fore.BLUE}Bot 100 trying to Report...  ')
time.sleep(1)
print(f'{Fore.GREEN}Successfully Reported!!\n')
time.sleep(2)


print(f'{Fore.YELLOW}FINISHED')
time.sleep(3)
print(f'{Fore.CYAN}From Aurel   ig: _.aurel_vllahi  ')


